### ISSUE TITLE
yum install collectd-java fail

### ISSUE THREAD

**Issue by hxzhaoyf** [signalfx/integrations#202]
hi, when I run yum install collectd-java,  output is :
```
No package collectd-java available.
Error: Nothing to do
```
i get message about "<Plugin java>" in collectd.conf, does it mean that i need not to yum install collectd-java?   Or  should I configure the source of yum?

Thanks a lot!

**Comment by dgriff-tools** [comment]
hi hxzhaoyf

first run:
yum install -y epel-release

then run:
yum install collectd-java

**Comment by hxzhaoyf** [comment]
@dgriff-tools thanks for your replay!  I find my collectd version is collectd 5.5.0,  <Plugin "java"> is build-in, and I need to change the collectd.conf both with 20-cassandra.conf and 10-jmx.conf. Thank you!
