### ISSUE TITLE
collectd-mongodb: Monitoring multiple instances.

### ISSUE THREAD

**Issue by OrBaruk** [signalfx/integrations#245]
The collectd-mongodb python plugin does not behave properly when set up to monitor multiple instances of mongodb.

**version**: collectd-5.7.1
**Config file:**
```
#mongodb.conf
LoadPlugin python
<Plugin python>
    ModulePath "/opt/collectd/plugins/"
    LogTraces true

    Import "mongodb"
    <Module mongodb>
        Host "127.0.0.1"
        Port "27017"
        User "collectd"
        Password "secret"
        Database "admin" "main"
    </Module>

    <Module mongodb>
        Host "127.0.0.1"
        Port "27018"
        User "collectd"
        Password "secret"
        Database "admin" "main"
    </Module>
</Plugin>
```

**Expected results:**
Collectd send metric from both instances running on the same machine

**Actual results:**
Only the instance in the port 27018 is being monitored

**Cause:**
Each module configuration causes collectd to call the function _config_ which overwrites the previous configuration. 

I have made changes to my local version of the plugin fixing the issue based on: http://stackoverflow.com/questions/27834815/how-to-run-multiple-instances-of-python-plugin-in-collectd

If there is interest I can create a pull-request on https://github.com/signalfx/collectd-mongodb

**Comment by molner** [comment]
Hi @OrBaruk - thank you for opening this issue.

Yes, a PR for this issue would be very much welcomed. Thank you in advance!

**Comment by OrBaruk** [comment]
Cool, I'll just wait for https://github.com/signalfx/collectd-mongodb/pull/19 to be resolved, since I had to change most of the configuration variables the merge would be a pain. 

I can also test my changes more in the meantime.
