### ISSUE TITLE
[collectd-haproxy] Instance name and long path problem

### ISSUE THREAD

**Issue by daks** [signalfx/integrations#410]
Hello,

I'm testing your haproxy collectd plugin https://github.com/signalfx/collectd-haproxy/blob/master/haproxy.py with collectd configured to send metrics to Graphite.
Haproxy global stats are fine but none of the backend or frontend I configured are available.

Digging a bit in the problem, I think the problem is the instance-name generated by the plugin. It looks like (as seen in logs) `[server_id=0,algorithm=roundrobin,service_name=BACKEND,unique_proxy_id=4,proxy_name=foo,process_id=1,cookie=,mode=http,ad` which seems to be the concatenation of all important parameters in the backend/frontend configuration.

In the Graphite server filesystem, the directory result is named `haproxy-[server_id=0,algorithm=roundrobin,service_name=BACKEND,unique_proxy_id=4,proxy_name=foo,process_id=1,cookie=,mode=http,ad`

As you can see the metric name is truncated, and it seems to create problems because in Grafana (frontend for Graphite) I see the metrics but I can't display any value.

Changing the code of haproxy.py

```
-    return "[%s]" % (",".join(dim_pairs))
+    return dimensions['proxy_name']
```
solved my problem, simply naming the instance by the proxy_name.

Is there any reason for having this so-long plugin-instance name? Don't you have any problem with this?

**Comment by daks** [comment]
**Update** : I changed again my code to return "%s_%s" % (dimensions['type'], dimensions['proxy_name']) with adds information about the backend/frontend type in the instance name.

**Comment by mstumpfx** [comment]
> Is there any reason for having this so-long plugin-instance name? Don't you have any problem with this?


We use plugin_instance to send our data dimensions to SignalFx in format [dim1=foo,dim2=bar,proxy_name=$pxname,type=$type ], which is why the plugin_instance ends up being so long.

**Comment by daks** [comment]
@mstumpfx so, this is specific to SignalFx integration? Which awaits a specific path format. 

Do you think it could be made modular, or optional?

If not, I'll just maintain a fork or a patch.

**Comment by daks** [comment]
@mstumpfx I think my needs are not specific, they are 'Graphite-standard', its just that your plugin isn't really compatible as-is with Graphite :)
